import "./firebase-config.js";

let code = new URLSearchParams(location.search).get("code")?.toUpperCase() || ""; let token = sessionStorage.getItem(`rice-survivor-admin-token-${code}`) || "";
const loginCard=document.querySelector("#login-card"),dashboard=document.querySelector("#admin-dashboard"),message=document.querySelector("#login-message");document.querySelector("#login-code").value=code;document.querySelector("#back-link").href=code?`/league.html?code=${code}`:"/";
const authFetch=(url,options={})=>fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${token}`}});
async function loadAdmin(){if(!code||!token)return;const response=await authFetch(`/api/leagues/${code}/admin`);if(!response.ok){token="";return;}const league=await response.json();loginCard.hidden=true;dashboard.hidden=false;document.querySelector("#admin-title").textContent=league.name;document.querySelector("#status-select").value=league.status;render(league.members);}
function render(members){const table=document.querySelector("#admin-table");table.innerHTML=members.length?`<div class="admin-row admin-row-head"><span>TEAM / PLAYER</span><span>SCORE</span><span>ADJUST</span></div>${members.sort((a,b)=>b.points-a.points).map(m=>`<div class="admin-row"><span><strong>${m.teamName}</strong><small>${m.playerName}</small></span><b>${m.points}</b><span class="score-actions"><button data-id="${m.id}" data-delta="-1" title="Subtract one point">−</button><button data-id="${m.id}" data-delta="1" title="Add one point">+</button></span></div>`).join("")}`:`<div class="empty-board">No one has joined this league yet.</div>`;}
document.querySelector("#admin-login").addEventListener("submit",async(event)=>{event.preventDefault();code=document.querySelector("#login-code").value.trim().toUpperCase();const pin=document.querySelector("#login-pin").value;const response=await fetch(`/api/leagues/${code}/admin/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin})});const result=await response.json();if(!response.ok){message.textContent=result.error;return;}token=result.token;sessionStorage.setItem(`rice-survivor-admin-token-${code}`,token);history.replaceState(null,"",`?code=${code}`);document.querySelector("#back-link").href=`/league.html?code=${code}`;loadAdmin();});
document.querySelector("#admin-table").addEventListener("click",async(event)=>{const button=event.target.closest("[data-id]");if(!button)return;button.disabled=true;await authFetch(`/api/leagues/${code}/admin/members/${button.dataset.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({delta:Number(button.dataset.delta)})});await loadAdmin();});
document.querySelector("#status-select").addEventListener("change",async(event)=>{await authFetch(`/api/leagues/${code}/admin/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:event.target.value})});});loadAdmin();
