export const contestants = [
  { id: 1, name: "Emma P", photo: "assets/contestants/Emma.png", college: "Chao", year: "Junior", major: "TBA", bio: "Profile coming soon." },
  { id: 2, name: "Carolina B", photo: "assets/contestants/Carolina.png", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 3, name: "Castaway 03", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 4, name: "Castaway 04", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 5, name: "Castaway 05", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 6, name: "Castaway 06", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 7, name: "Castaway 07", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 8, name: "Castaway 08", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 9, name: "Castaway 09", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 10, name: "Castaway 10", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 11, name: "Castaway 11", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 12, name: "Castaway 12", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 13, name: "Castaway 13", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 14, name: "Castaway 14", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 15, name: "Castaway 15", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 16, name: "Castaway 16", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 17, name: "Castaway 17", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
  { id: 18, name: "Castaway 18", photo: "", college: "TBA", year: "TBA", major: "TBA", bio: "Profile coming soon." },
];
